swagger: '2.0'
info:
  version: '0.1.0'
  title: User API
  description: An API managing users and teams
host: localhost:8080
basePath: /api
schemes:
  - http
paths:
  /users:
    post:
      description: create a user
      operationId: createUser
      consumes:
        - application/json
      parameters:
        - name: user
          in: body
          required: true
          schema:
            $ref: '#/definitions/User'
      responses:
        '201':
          description: Created
          schema:
            type: object
        '400':
          description: Bad request
          schema:
            type: string
    get:
      description: get the list of all users
      operationId: getUsers
      produces:
        - application/json
      responses:
        '200':
          description: success
          schema:
            type: array
            items:
              $ref: '#/definitions/User'

  /users/{id}:
    get:
      description: get a specific User
      operationId: getUser
      parameters:
        - name: id
          in: path
          type: integer
          format: int64
          required: true
          description: user's id
          schema:
            type: integer
      produces:
        - application/json
      responses:
        '200':
          description: success
          schema:
            $ref: '#/definitions/User'

  /users/get:
    get:
      description: get a specific User with his username
      operationId: getUser
      parameters:
        - name: username
          in: query
          required: true
          description: user's username
          schema:
            type: string
      produces:
        - application/json
      responses:
        '200':
          description: success
          schema:
            $ref: '#/definitions/User'



definitions:
  User:
    type: object
    properties:
      username:
        type: string
      email:
        type: string
        format: email
      password:
        type: string
      firstName:
        type: string
      lastName:
        type: string
      displayName:
        type: string
    required:
        - username
        - email
        - password

