version: '3'

services:
  roach-one:
    image: cockroachdb/cockroach:v1.1.2
    command: start --insecure
    ports:
      - 9090:8080
      - 26257:26257
    networks:
      - roachnet
  roach-two:
    image: cockroachdb/cockroach:v1.1.2
    command: start --insecure --join=roach-one
    networks:
      - roachnet
  roach-three:
    image: cockroachdb/cockroach:v1.1.2
    command: start --insecure --join=roach-one
    networks:
      - roachnet
  init-data:
    image: jbergknoff/postgresql-client:latest
    command: -p 26257 -h roach-one -U root -c 'CREATE DATABASE "users-service"'
    networks:
      - roachnet
    depends_on:
      - roach-one

networks:
  roachnet: